# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTipNo_C <- function(treeTip, OTU) {
    .Call(`_Apoderoides_getTipNo_C`, treeTip, OTU)
}

extractOTUbyRankName_C <- function(rankName, treeTip, rankList) {
    .Call(`_Apoderoides_extractOTUbyRankName_C`, rankName, treeTip, rankList)
}

getRankCentroid_C <- function(rankName, dropIndex, treeTip, treeMatCol0, treeMatCol1, rankList, show_progress = 0L, num_threads = 1L) {
    .Call(`_Apoderoides_getRankCentroid_C`, rankName, dropIndex, treeTip, treeMatCol0, treeMatCol1, rankList, show_progress, num_threads)
}

getAllCentroids_C <- function(treeTip, allRankNames, treeMatCol0, treeMatCol1, rankList, show_progress = 0L, num_threads = 1L) {
    .Call(`_Apoderoides_getAllCentroids_C`, treeTip, allRankNames, treeMatCol0, treeMatCol1, rankList, show_progress, num_threads)
}

calcIntScore_C <- function(treeTip, treeMatCol0, treeMatCol1, OTU, allCentroids, allRankNames, rankList) {
    .Call(`_Apoderoides_calcIntScore_C`, treeTip, treeMatCol0, treeMatCol1, OTU, allCentroids, allRankNames, rankList)
}

findSubTips_C <- function(treeTip, treeMatCol0, treeMatCol1, node) {
    .Call(`_Apoderoides_findSubTips_C`, treeTip, treeMatCol0, treeMatCol1, node)
}

calcOutScore_C <- function(treeTip, treeMatCol0, treeMatCol1, OTU, allCentroids, allRankNames, rankList, dropIndex) {
    .Call(`_Apoderoides_calcOutScore_C`, treeTip, treeMatCol0, treeMatCol1, OTU, allCentroids, allRankNames, rankList, dropIndex)
}

